name: CI

on:
  push:
    branches:
      - 'main'
      - 'release-v**'
      - 'full-sonar-analysis-**'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"


jobs:
  build:
    name: Build OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout sources for powsybl-core
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-core
          ref: refs/heads/main

      - name: Checkout sources for powsybl-open-loadflow
        uses: actions/checkout@v1
        with:
          repository: powsybl/powsybl-open-loadflow
          ref: refs/heads/report_v2

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build powsybl-core
        run: mvn --batch-mode -Pjacoco --file ../powsybl-core/pom.xml install

      - name: Build powsybl-open-loadflow
        run: mvn --batch-mode -Pjacoco --file ../powsybl-open-loadflow/pom.xml install

      - name: Build with Maven
        run: mvn --batch-mode -Pjacoco install

      - name: Run load flow integration test
        run: mvn verify

      - name: Run SonarCloud analysis
        if: matrix.os == 'ubuntu-latest'
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=powsybl-ci-github
          -Dsonar.projectKey=com.powsybl:powsybl-integration-test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
